# Generated by Django 5.1.2 on 2024-11-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telifon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('narx', models.CharField(default="so'm", max_length=50)),
                ('rasim', models.ImageField(upload_to='media')),
                ('vaqt', models.DateField()),
                ('malimot', models.TextField()),
            ],
        ),
    ]
